{% set name = "lmod" %}
{% set version = "7.7.31" %}
{% set sha256 = "97ce9e81545a7f13c18da82e2d0af8b4f6aa83f3ce7f86e81e3d9e837ec6a23c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/TACC/Lmod/archive/{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [win]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - llvm  # [osx]
    - zlib
    - lua
    - luarocks
    - lua-luafilesystem
    - lua-luaposix
  run:
    - zlib
    - lua
    - luarocks
    - lua-luafilesystem
    - lua-luaposix

test:
  commands:
    - type module
    - env | grep MODULEPATH_ROOT
    - env | grep MODULEPATH
    - env | grep MODULESHOME

about:
  home: https://github.com/TACC/Lmod
  license: MIT
  license_family: MIT
  #license_file: LICENSE.txt
  summary: 'Lmod: An Environment Module System based on Lua, Reads TCL Modules, Supports a Software Hierarchy'
  dev_url: https://github.com/TACC/Lmod
  doc_url: http://lmod.readthedocs.org/

extra:
  recipe-maintainers:
    - jerowe
