{% set name = "lmod" %}
{% set version = "7.8" %}
{% set sha256 = "40388380a36a00c3ce929a9f88c8fffc93deeabf87a7c3f8864a82acad38c3ba" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/TACC/Lmod/archive/{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [win]
  number: 0

requirements:
  build:
    - gcc  # [linux]
    - llvm  # [osx]
    - zlib 1.2.*
    - lua
    - luarocks
    - lua-luafilesystem
    - lua-luaposix 
  run:
    - libgcc  # [linux]
    - zlib 1.2.*
    - lua
    - luarocks
    - lua-luafilesystem
    - lua-luaposix 

test:
  commands:
    - type module
    - env | grep MODULEPATH_ROOT
    - env | grep MODULEPATH
    - env | grep MODULESHOME

about:
  home: https://github.com/TACC/Lmod
  license: MIT
  license_family: MIT
  #license_file: LICENSE.txt
  summary: 'Lmod: An Environment Module System based on Lua, Reads TCL Modules, Supports a Software Hierarchy'
  dev_url: https://github.com/TACC/Lmod
  doc_url: http://lmod.readthedocs.org/

extra:
  recipe-maintainers:
    - jerowe 
